version: '3.4'

services:
  influxdb:
    image: influxdb:alpine
    volumes:
      - /srv/data/docker/containers/influxdb-grafana-app/influxdb/data:/var/lib/influxdb
    environment:
      INFLUXDB_ADMIN_ENABLED:true
      INFLUXDB_ADMIN_USER:
      INFLUXDB_ADMIN_PASSWORD:
      TZ:Europe/Rome

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - /srv/data/docker/containers/influxdb-grafana-app/grafana/data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD:
      TZ:Europe/Rome
    depends_on:
      - infuxdb
