version: '3.4'

services:
  influxdb:
    image: influxdb:alpine
    ports:
      - 8086:8086
    volumes:
      - /srv/data/docker/containers/influxdb-grafana-app/influxdb/data:/var/lib/influxdb
    environment:
      INFLUXDB_ADMIN_ENABLED:
      # yes/no
      INFLUXDB_ADMIN_USER:
      INFLUXDB_ADMIN_PASSWORD:
      INFLUXDB_GRAPHITE_ENABLED:
      # true/false
      TZ:
      # 4 ex: Europe/Rome

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
      - 2003:2003
      # graphite support
    volumes:
      - /srv/data/docker/containers/influxdb-grafana-app/grafana/data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD:
      GF_SECURITY_ADMIN_USER:
      TZ:
      # 4 ex: Europe/Rome
    depends_on:
      - infuxdb
