version: '3.4'

services:
  influxdb:
    image: influxdb:alpine
    ports:
      - 8086:8086
      - 2003:2003
      - 4242:4242
      # graphite support

    volumes:
      - /srv/data/docker/containers/influxdb-grafana-app/influxdb/data:/var/lib/influxdb
    environment:
      INFLUXDB_ADMIN_ENABLED:
      # yes/no
      INFLUXDB_ADMIN_USER:
      INFLUXDB_ADMIN_PASSWORD:
      INFLUXDB_GRAPHITE_ENABLED:
      # true/false
      INFLUXDB_GRAPHITE_DATABASE:
      # default database name
      INFLUXDB_OPENTSDB_ENABLED:
      # true/false
      INFLUXDB_OPENTSDB_BIND_ADDRESS:
      # default ":4242"
      INFLUXDB_OPENTSDB_DATABASE:
      # database name
      TZ:
      # 4 ex: Europe/Rome
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - /srv/data/docker/containers/influxdb-grafana-app/grafana/data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD:
      GF_SECURITY_ADMIN_USER:
      GF_SMTP_ENABLED:
      # true/false
      GF_SMTP_HOST:
      # smtp server to use. ex: 192.168.1.1:25
      GF_SMTP_FROM_ADDRESS:
      # sender email address
      GF_SMTP_FROM_NAME:
      # sender email name. defaults to Grafana
      GF_SMTP_EHLO_IDENTITY:
      # Name to be used as client identity for EHLO in SMTP dialog, defaults to instance_name.
      TZ:
      # 4 ex: Europe/Rome
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1      
    depends_on:
      - infuxdb
